version: 2
builds:
  - env:
      - CGO_ENABLED=0 # Disable CGO for static binaries
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: . # Path to your main package
    binary: blockinfile # Name of the generated binary

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"